# Theory of Complex Vector Spaces
Complex vector spaces extend the idea of real vector spaces by allowing vectors to have complex numbers as their components. In these spaces, vectors can be added together and multiplied by complex scalars to produce new vectors. Key operations in complex vector spaces include vector addition, scalar multiplication, vector negation, and complex conjugation.

# Creating complex column vectors

In [176]:
import numpy as np

# Define a 2x2 square matrix
matrix = np.array([[2, 3],
                   [1, 4]])

# Define a vector of size 2
vector = np.array([5, 6])

# Multiply the matrix by the vector
result = np.dot(matrix, vector)

# Display the result
print("Matrix:\n", matrix)
print("\nVector:\n", vector)
print("\nResult of multiplication:\n", result)


Matrix:
 [[2 3]
 [1 4]]

Vector:
 [5 6]

Result of multiplication:
 [28 29]


## Manipulating Complex Column Vectors using NumPy
Here we demonstrate how to manipulate complex column vectors using NumPy, including operations like sum, negation, multiplication by a scalar, transpose, adjunct, and conjugate.

In [177]:

import numpy as np

# Define two complex column vectors
v1 = np.array([[2+3j], [5-4j], [1+1j]])
v2 = np.array([[1-1j], [3+2j], [4-4j]])

# Sum
sum_v = v1 + v2

# Negation
neg_v1 = -v1

# Multiplication by a scalar
scalar = 2 + 1j
mult_v1 = v1 * scalar

# Transpose
transpose_v1 = v1.T

# Adjunct (Conjugate transpose)
adjunct_v1 = v1.T.conj()

# Conjugate
conjugate_v1 = np.conjugate(v1)

(sum_v, neg_v1, mult_v1, transpose_v1, adjunct_v1, conjugate_v1)


(array([[3.+2.j],
        [8.-2.j],
        [5.-3.j]]),
 array([[-2.-3.j],
        [-5.+4.j],
        [-1.-1.j]]),
 array([[ 1.+8.j],
        [14.-3.j],
        [ 1.+3.j]]),
 array([[2.+3.j, 5.-4.j, 1.+1.j]]),
 array([[2.-3.j, 5.+4.j, 1.-1.j]]),
 array([[2.-3.j],
        [5.+4.j],
        [1.-1.j]]))

# Theory of Vector Spaces using Matrices
In the context of matrices, vector spaces can be defined where each vector is a matrix of a particular size. Operations on these matrix-vector spaces include matrix addition, scalar multiplication, matrix negation, transpose, adjunct, and conjugate. In this section, we focus on square matrices of size 3x3.

## Manipulating Square Matrices using NumPy
Examples of how to manipulate 3x3 square matrices using NumPy, showing operations such as sum, negation, multiplication by a scalar, conjugate, transpose, and adjunct.

In [178]:

# Define two 3x3 complex matrices
m1 = np.array([[2+3j, 4-1j, 0], 
               [1+1j, 3+3j, 5], 
               [4, 6-2j, 1-1j]])
m2 = np.array([[1, 2+1j, 3-3j], 
               [0, -1+2j, 1-2j], 
               [3+3j, 2, 4+4j]])

# Sum
sum_m = m1 + m2

# Negation
neg_m1 = -m1

# Multiplication by a scalar
scalar = 0.5 + 0.5j
mult_m1 = m1 * scalar

# Conjugate
conjugate_m1 = np.conjugate(m1)

# Transpose
transpose_m1 = m1.T

# Adjunct (Conjugate transpose)
adjunct_m1 = m1.T.conj()

(sum_m, neg_m1, mult_m1, conjugate_m1, transpose_m1, adjunct_m1)


(array([[3.+3.j, 6.+0.j, 3.-3.j],
        [1.+1.j, 2.+5.j, 6.-2.j],
        [7.+3.j, 8.-2.j, 5.+3.j]]),
 array([[-2.-3.j, -4.+1.j, -0.-0.j],
        [-1.-1.j, -3.-3.j, -5.-0.j],
        [-4.-0.j, -6.+2.j, -1.+1.j]]),
 array([[-0.5+2.5j,  2.5+1.5j,  0. +0.j ],
        [ 0. +1.j ,  0. +3.j ,  2.5+2.5j],
        [ 2. +2.j ,  4. +2.j ,  1. +0.j ]]),
 array([[2.-3.j, 4.+1.j, 0.-0.j],
        [1.-1.j, 3.-3.j, 5.-0.j],
        [4.-0.j, 6.+2.j, 1.+1.j]]),
 array([[2.+3.j, 1.+1.j, 4.+0.j],
        [4.-1.j, 3.+3.j, 6.-2.j],
        [0.+0.j, 5.+0.j, 1.-1.j]]),
 array([[2.-3.j, 1.-1.j, 4.-0.j],
        [4.+1.j, 3.-3.j, 6.+2.j],
        [0.-0.j, 5.-0.j, 1.+1.j]]))

## Checking the Dimension of a Matrix
We can check the dimension of a matrix using the `.shape` attribute.

In [179]:
# Checking the dimension of matrix1
m1.shape

(3, 3)

## Action of a Matrix on a Vector
Finally, examples of how to use Python to multiply a 3x3 square matrix by a 3x1 column vector.

In [180]:

# Multiplying a 3x3 matrix by a 3x1 vector
result = np.dot(m1, v1)
result


array([[11. -9.j],
       [31.+13.j],
       [32.-22.j]])

# Exercises on Complex Vectors and Matrices with Concrete Cases

This set of exercises focuses on operations with complex column vectors and complex square matrices, including concrete cases with vectors and matrices written in LaTeX format.

## Complex Column Vector Operations

### Exercise 1: Sum of Two Complex Vectors
Given two complex vectors 
$ v1 = \begin{bmatrix} 1 + 2i \\ 3 - i \end{bmatrix} $ 
and 
$ v2 = \begin{bmatrix} 2 - i \\ 4 + 2i \end{bmatrix} $, 
find their sum.

### Exercise 2: Negation of a Complex Vector
Given a complex vector 
$ v = \begin{bmatrix} 2 + 3i \\ 1 - 2i \end{bmatrix} $, 
find its negation.

### Exercise 3: Multiplication of a Complex Vector by a Scalar
Multiply the complex vector 
$ v = \begin{bmatrix} 1 - i \\ 2 + 2i \end{bmatrix} $ 
by the complex scalar $$ 3 + i $$.

### Exercise 4: Transpose of a Complex Vector
Find the transpose of the complex vector 
$ v = \begin{bmatrix} 2 - i \\ 3 + 4i \end{bmatrix} $.

### Exercise 5: Conjugate of a Complex Vector
Compute the conjugate of the complex vector 
$ v = \begin{bmatrix} 1 + i \\ 2 - 3i \end{bmatrix} $.

### Exercise 6: Adjunct (Conjugate Transpose) of a Complex Vector
Find the adjunct (or conjugate transpose) of the complex vector 
$ v = \begin{bmatrix} 1 - 2i \\ 3 + i \end{bmatrix} $.

## Complex Square Matrix Operations

### Exercise 7: Sum of Two Complex Matrices
Given two complex matrices 
$ m1 = \begin{bmatrix} 1 + i & 2 - i \\ 3 + 2i & 4 \end{bmatrix} $
and 
$ m2 = \begin{bmatrix} 2 - 3i & 1 \\ i & 2 + 2i \end{bmatrix} $, 
calculate their sum.

### Exercise 8: Negation of a Complex Matrix
Find the negation of the complex matrix 
$ m = \begin{bmatrix} 2 + i & 3 \\ 1 - i & 2 + 2i \end{bmatrix} $.

### Exercise 9: Multiplication of a Complex Matrix by a Scalar
Multiply the complex matrix 
$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + i & 4 - 2i \end{bmatrix} $ 
by the complex scalar $$ 2 + 3i $$.

### Exercise 10: Conjugate of a Complex Matrix
Compute the conjugate of the complex matrix 
$ m = \begin{bmatrix} 1 + i & 2 \\ 3 - i & 4 + 2i \end{bmatrix} $.

### Exercise 11: Transpose of a Complex Matrix
Find the transpose of the complex matrix 
$ m = \begin{bmatrix} 1 - i & 2 + 2i \\ 3 & 4 - i \end{bmatrix} $.

### Exercise 12: Adjunct (Conjugate Transpose) of a Complex Matrix
Calculate the adjunct (or conjugate transpose) of the complex matrix 
$ m = \begin{bmatrix} 1 + 2i & 3 - i \\ 4 & 5 + i \end{bmatrix} $.

### Exercise 13: Checking the Dimensions of a Matrix
Determine the dimensions of the complex matrix 
$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + 2i & 4 - i \end{bmatrix} $.

## Multiplication of Matrices and Vectors

### Exercise 14: Multiplying a Complex Square Matrix by a Complex Column Vector
Multiply the complex square matrix 
$ m = \begin{bmatrix} 1 + i & 2 - i \\ 3 & 4 + i \end{bmatrix} $ 
by the complex column vector 
$ v = \begin{bmatrix} 2 - i \\ 1 + 3i \end{bmatrix} $.

## Instructions
For each exercise, ensure to display both the input (vectors/matrices) and the result of the operation.Use NumPy for these exercises to practice handling complex numbers and matrix operations in Python.


<h1 style="text-align: center;">Solución de los Ejercicios</h1>

### Exercise 1: Sum of Two Complex Vectors

$$ \begin{bmatrix} 1 + 2i \\ 3 - i \end{bmatrix} + \begin{bmatrix} 2 - i \\ 4 + 2i \end{bmatrix} =  \begin{bmatrix} (1 + 2i) + (2 - i)\\ (3 - i) + (4 + 2i)\end{bmatrix} = \begin{bmatrix} 3 + i \\ 7 + i \end{bmatrix} $$ 


In [181]:
# Exercise 1: Sum of Two Complex Vectors
import numpy as np

def format_complex(c):
    if (c.imag == 1 or c.imag == -1):
        if(c.real == 0):
            return f"{'      '}i{'   '}" 
        else:
            return f"{c.real}{' + ' if c.imag >= 0 else ' - '}i{'   '}"
    if (c.imag == 0):
        return f"{c.real}{'       '}"
    elif(c.real == 0):
        if (c.imag < 0):
            return f"{'     '}{c.imag}i"
        else:
            return f"{'      '}{c.imag}i"
    return f"{c.real}{' + ' if c.imag >= 0 else ' - '}{abs(c.imag)}i"


def format_printed(a,b,c):
    print("La suma de los vectores a y b ")
    print("  v1 = ", ' \n        '.join(format_complex(x) for x in a))
    print()
    print("  v2 = ", ' \n        '.join(format_complex(x) for x in b))
    print()
    print("v1+v2= ",' \n        '.join(format_complex(x) for x in c))
    
    
def sum_Complex_Vectors(v1,v2):
    a = np.array(v1)
    b = np.array(v2)
    if (len(a) == len(b)) == True:
        suma = np.add(a,b)
        format_printed(a,b,suma)
    else:
        raise Exception ("Error: Los vectores no son del mismo tamaño")
    

v1 = [1+2j, 3-1j]
v2 = [2-1j, 4+2j]

sum_Complex_Vectors(v1,v2)

La suma de los vectores a y b 
  v1 =  1.0 + 2.0i 
        3.0 - i   

  v2 =  2.0 - i    
        4.0 + 2.0i

v1+v2=  3.0 + i    
        7.0 + i   


### Exercise 2: Negation of a Complex Vector

$$  v = \begin{bmatrix} 2 + 3i \\ 1 - 2i \end{bmatrix} $$ 
$$ -v =\begin{bmatrix} -2 - 3i \\ -1 + 2i \end{bmatrix} $$

In [182]:
#Exercise 2: Negation of a Complex Vector
import numpy as np

def format_complex(c):
    if (c.imag == 1 or c.imag == -1):
        if(c.real == 0):
            return f"{'      '}i{'   '}" 
        else:
            return f"{c.real}{' + ' if c.imag >= 0 else ' - '}i{'   '}"
    if (c.imag == 0):
        return f"{c.real}{'       '}"
    elif(c.real == 0):
        if (c.imag < 0):
            return f"{'     '}{c.imag}i"
        else:
            return f"{'      '}{c.imag}i"
    return f"{c.real}{' + ' if c.imag >= 0 else ' - '}{abs(c.imag)}i"

def format_printed(a,b):
    print("La negacion del vector")
    print("   v = ",' \n        '.join(format_complex(x) for x in a))
    print("  ¬v = ",' \n        '.join(format_complex(x) for x in b))

def negation_Complex_Vector(a):
    a = np.array(a)
    v = np.negative(a)
    format_printed(a,v)

v = [2+3j,1-2j]
negation_Complex_Vector(v)
    

La negacion del vector
   v =  2.0 + 3.0i 
        1.0 - 2.0i
  ¬v =  -2.0 - 3.0i 
        -1.0 + 2.0i


### Exercise 3: Multiplication of a Complex Vector by a Scalar

$$
(3 + i) \cdot \begin{bmatrix} 1 - i \\ 2 + 2i \end{bmatrix} = \begin{bmatrix} 
(3 + i) \cdot (1 - i) \\ 
(3 + i) \cdot (2 + 2i) 
\end{bmatrix} = \begin{bmatrix} 
4 - 2i \\ 
4 + 8i 
\end{bmatrix}
$$



In [183]:
# Exercise 3: Multiplication of a Complex Vector by a Scalar
import numpy as np
def format_complex(c):
    if (c.imag == 1 or c.imag == -1):
        if(c.real == 0):
            return f"{'      '}i{'   '}" 
        else:
            return f"{c.real}{' + ' if c.imag >= 0 else ' - '}i{'   '}"
    if (c.imag == 0):
        return f"{c.real}{'       '}"
    elif(c.real == 0):
        if (c.imag < 0):
            return f"{'     '}{c.imag}i"
        else:
            return f"{'      '}{c.imag}i"
    return f"{c.real}{' + ' if c.imag >= 0 else ' - '}{abs(c.imag)}i"

def format_printed(a,b,c):
    print("La multiplicación del vector")
    print("      v = ",' \n           '.join(format_complex(x) for x in a))
    print("y el escalar ", format_complex(b), "es: ")
    print("  s * V = ",' \n           '.join(format_complex(x) for x in c))

def multiplication_Complex_vector_scalar(vector,scalar):
    v = np.array(vector)
    multiplication = np.multiply(scalar,v)
    format_printed(v,scalar,multiplication)

vector = [1-1j,2+2j]
scalar = 3+1j
multiplication_Complex_vector_scalar(vector,scalar)



La multiplicación del vector
      v =  1.0 - i    
           2.0 + 2.0i
y el escalar  3.0 + i    es: 
  s * V =  4.0 - 2.0i 
           4.0 + 8.0i


### Exercise 4: Transpose of a Complex Vector

$$ v = \begin{bmatrix} 2 - i \\ 3 + 4i \end{bmatrix}$$ 
$$ v^{T} = \begin{bmatrix} 2 - i , 3 + 4i \end{bmatrix} $$ 

In [184]:
import numpy as np

def format_complex(c):
    if (c.imag == 1 or c.imag == -1):
        if(c.real == 0):
            return f"{'      '}i{'   '}" 
        else:
            return f"{c.real}{' + ' if c.imag >= 0 else ' - '}i{'   '}"
    if (c.imag == 0):
        return f"{c.real}{'       '}"
    elif(c.real == 0):
        if (c.imag < 0):
            return f"{'     '}{c.imag}i"
        else:
            return f"{'      '}{c.imag}i"
    return f"{c.real}{' + ' if c.imag >= 0 else ' - '}{abs(c.imag)}i"

def format_printed(a,b):
    m = 0
    for i in a:
        if (m > 0):
            m += 1
            print ("     ", ' '.join(format_complex(x) for x in i) )
        else:
            m += 1
            print(" v = ", ' '.join(format_complex(x) for x in i)) 
    print("la transpuesta es:", str(b))

def transpose(a):
    a = np.array(a)
    b = a.T
    format_printed(a,b)

a = [[2-1j],[3+4j]]
transpose(a)


 v =  2.0 - i   
      3.0 + 4.0i
la transpuesta es: [[2.-1.j 3.+4.j]]


### Exercise 5: Conjugate of a Complex Vector

$$ v = \begin{bmatrix} 1 + i \\ 2 - 3i \end{bmatrix} $$
$$  \overline{v} = \begin{bmatrix} 1 - i \\ 2 -+ 3i \end{bmatrix}$$ 

In [185]:
import numpy as np

def format_complex(c):
    if (c.imag == 1 or c.imag == -1):
        if(c.real == 0):
            return f"{'      '}i{'   '}" 
        else:
            return f"{c.real}{' + ' if c.imag >= 0 else ' - '}i{'   '}"
    if (c.imag == 0):
        return f"{c.real}{'       '}"
    elif(c.real == 0):
        if (c.imag < 0):
            return f"{'     '}{c.imag}i"
        else:
            return f"{'      '}{c.imag}i"
    return f"{c.real}{' + ' if c.imag >= 0 else ' - '}{abs(c.imag)}i"

def format_printed(a,b):
    print("El conjugado del vector")
    print("     v =  ",' \n           '.join(format_complex(x) for x in a))
    print("     es: ", end=" ")
    print("",' \n           '.join(format_complex(x) for x in b))

def conjugateV(a):
    a = np.array(a)
    b = a.conjugate()
    format_printed(a,b)

a = [1+1j,2-3j]
conjugateV(a)


El conjugado del vector
     v =   1.0 + i    
           2.0 - 3.0i
     es:   1.0 - i    
           2.0 + 3.0i


### Exercise 6: Adjunct (Conjugate Transpose) of a Complex Vector
 
$$ v = \begin{bmatrix} 1 - 2i \\ 3 + i \end{bmatrix} $$
$$ \overline{v^{T}}  \begin{bmatrix} 1 + 2i & 3 - i \end{bmatrix} $$


In [186]:
import numpy as np

def format_complex(c):
    if (c.imag == 1 or c.imag == -1):
        if(c.real == 0):
            return f"{'      '}i{'   '}" 
        else:
            return f"{c.real}{' + ' if c.imag >= 0 else ' - '}i{'   '}"
    if (c.imag == 0):
        return f"{c.real}{'       '}"
    elif(c.real == 0):
        if (c.imag < 0):
            return f"{'     '}{c.imag}i"
        else:
            return f"{'      '}{c.imag}i"
    return f"{c.real}{' + ' if c.imag >= 0 else ' - '}{abs(c.imag)}i"

def format_printed(a,b):
    print("La adjunta del vector")
    m = 0
    for i in a:
        if (m > 0):
            m += 1
            print ("     ", ' '.join(format_complex(x) for x in i) )
        else:
            m += 1
            print(" a = ", ' '.join(format_complex(x) for x in i))
    print("es: [",end="")
    for i in b:
        print(' , '.join(format_complex(x) for x in i),end="")
    print("]")
    

def adjunct(a):
    a = np.array(a)
    b = (a.T).conjugate()
    format_printed(a,b)

a = [[1-2j],[3+1j]]
adjunct(a)

La adjunta del vector
 a =  1.0 - 2.0i
      3.0 + i   
es: [1.0 + 2.0i , 3.0 - i   ]


### Exercise 7: Sum of Two Complex Matrices
 
$$ \begin{bmatrix} 1 + i & 2 - i \\ 3 + 2i & 4 \end{bmatrix}  + 
  \begin{bmatrix} 2 - 3i & 1 \\ i & 2 + 2i \end{bmatrix} =   \begin{bmatrix} (1 + i)+(2 - 3i) & (3 + 2i)+1 \\ (2 - i )+i & 4+(2 + 2i) \end{bmatrix} = \begin{bmatrix} 3 - 2i & 3 - i \\ 3 + 3i & 6 + 4i \end{bmatrix} $$

In [187]:
import numpy as np

def format_complex(c):
    if (c.imag == 1 or c.imag == -1):
        if(c.real == 0):
            return f"{'      '}i{'   '}" 
        else:
            return f"{c.real}{' + ' if c.imag >= 0 else ' - '}i{'   '}"
    if (c.imag == 0):
        return f"{c.real}{'       '}"
    elif(c.real == 0):
        if (c.imag < 0):
            return f"{'     '}{c.imag}i"
        else:
            return f"{'      '}{c.imag}i"
    return f"{c.real}{' + ' if c.imag >= 0 else ' - '}{abs(c.imag)}i"

def format_printed(a,b,c):
    print("La suma de las matrices")
    m = 0
    for i in a:
        if (m > 0):
            m += 1
            print("     ", '  '.join(format_complex(x) for x in i) )
        else:
            m += 1
            print(" a = ", '  '.join(format_complex(x) for x in i))
    print()
    m = 0
    for i in b:
        if (m > 0):
            m += 1
            print ("     ", '  '.join(format_complex(x) for x in i) )
        else:
            m += 1
            print(" b = ", '  '.join(format_complex(x) for x in i))
    print()
    print(" es: ", end= "")
    m = 0
    for i in c:
        if (m > 0):
            m += 1
            print("     ", '  '.join(format_complex(x) for x in i) )
        else:
            m += 1
            print("", '  '.join(format_complex(x) for x in i))
    

def sum_Complex_Matrices(a,b):
    a = np.array(a)
    b = np.array(b)
    if len_matrix(a,b) == True:
        c = np.add(a,b)
        format_printed(a,b,c)
    else:
        raise Exception("Error: Las matrices no pertenecen al mismo R, no se puede reaizar la suma")
    

def len_matrix(a,b):
    if len(a) == len(b):
        if len(a[0])==len(b[0]):
            return True
        return False
    return False
a = [[1+1j,2-1j],[3+2j,4]]
b = [[2-3j,1],[1j,2+2j]]
sum_Complex_Matrices(a,b)

La suma de las matrices
 a =  1.0 + i     2.0 - i   
      3.0 + 2.0i  4.0       

 b =  2.0 - 3.0i  1.0       
            i     2.0 + 2.0i

 es:  3.0 - 2.0i  3.0 - i   
      3.0 + 3.0i  6.0 + 2.0i


### Exercise 8: Negation of a Complex Matrix
Find the negation of the complex matrix 
$$ m = \begin{bmatrix} 2 + i & 3 \\ 1 - i & 2 + 2i \end{bmatrix} $$
$$ -m = \begin{bmatrix} -2 - i & -3 \\ -1 + i & -2 - 2i \end{bmatrix} $$



In [188]:
import numpy as np

def format_complex(c):
    if (c.imag == 1 or c.imag == -1):
        if(c.real == 0):
            return f"{'      '}i{'   '}" 
        else:
            return f"{c.real}{' + ' if c.imag >= 0 else ' - '}i{'   '}"
    if (c.imag == 0):
        return f"{c.real}{'       '}"
    elif(c.real == 0):
        if (c.imag < 0):
            return f"{'     '}{c.imag}i"
        else:
            return f"{'      '}{c.imag}i"
    return f"{c.real}{' + ' if c.imag >= 0 else ' - '}{abs(c.imag)}i"

def format_printed(a,b):
    print("La negación de la matriz")
    m = 0
    for i in a:
        if (m > 0):
            m += 1
            print("      ", '  '.join(format_complex(x) for x in i) )
        else:
            m += 1
            print("  m = ", '  '.join(format_complex(x) for x in i))
    print()
    m = 0
    print("es: ")
    for i in b:
        if (m > 0):
            m += 1
            print("      ", '  '.join(format_complex(x) for x in i) )
        else:
            m += 1
            print(" -m = ", '  '.join(format_complex(x) for x in i))
    print()
   
def negation_Complex_Matrix(a):
    a = np.array(a)
    negation_A = np.negative(a)
    format_printed(a,negation_A)

m = [[2+1j,3],[1-1j,2+2j]]
negation_Complex_Matrix(m)
    

La negación de la matriz
  m =  2.0 + i     3.0       
       1.0 - i     2.0 + 2.0i

es: 
 -m =  -2.0 - i     -3.0       
       -1.0 + i     -2.0 - 2.0i



### Exercise 9: Multiplication of a Complex Matrix by a Scalar
Multiply the complex matrix 
$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + i & 4 - 2i \end{bmatrix} $ 
by the complex scalar $$ k = 2 + 3i $$

$$
k \cdot m = 2 + 3i \cdot \begin{bmatrix} 1 - i & 2 \\ 3 + i & 4 - 2i \end{bmatrix}  = \begin{bmatrix} (2 + 3i) \cdot (1 - i)  & (2 + 3i) \cdot 2 \\ (2 + 3i) \cdot (3 + i) & (2 + 3i) \cdot (4 - 2i) \end{bmatrix} = \begin{bmatrix} 5+i & 4+6i \\ 3+11i & 14+8i\end{bmatrix}$$

In [189]:
import numpy as np

def format_complex(c):
    if (c.imag == 1 or c.imag == -1):
        if(c.real == 0):
            return f"{'      '}i{'   '}" 
        else:
            return f"{c.real}{' + ' if c.imag >= 0 else ' - '}i{'   '}"
    if (c.imag == 0):
        return f"{c.real}{'       '}"
    elif(c.real == 0):
        if (c.imag < 0):
            return f"{'     '}{c.imag}i"
        else:
            return f"{'      '}{c.imag}i"
    return f"{c.real}{' + ' if c.imag >= 0 else ' - '}{abs(c.imag)}i"

def format_printed(a,b,c):
    print("La multiplicación del escalar = ",format_complex(a)," y la matriz")
    m = 0
    for i in b:
        if (m > 0):
            m += 1
            print("       ", '  '.join(format_complex(x) for x in i) )
        else:
            m += 1
            print("   m = ", '  '.join(format_complex(x) for x in i))
    print()
    m = 0
    print("el resultado es: ")
    for i in c:
        if (m > 0):
            m += 1
            print("       ", '  '.join(format_complex(x) for x in i) )
        else:
            m += 1
            print(" s·m = ", '  '.join(format_complex(x) for x in i))
    print()

def multiplication_Complex_Matrix_Scalar(scalar,matrix):
    matrix = np.array(matrix)
    result = np.multiply(scalar,matrix)
    format_printed(scalar,matrix,result)

scalar = 2+3j
matrix = [[1-1j,2],[3+1j,4-2j]]
multiplication_Complex_Matrix_Scalar(scalar,matrix)

La multiplicación del escalar =  2.0 + 3.0i  y la matriz
   m =  1.0 - i     2.0       
        3.0 + i     4.0 - 2.0i

el resultado es: 
 s·m =  5.0 + i     4.0 + 6.0i
        3.0 + 11.0i  14.0 + 8.0i



### Exercise 10: Conjugate of a Complex Matrix
Compute the conjugate of the complex matrix 
$$ m = \begin{bmatrix} 1 + i & 2 \\ 3 - i & 4 + 2i \end{bmatrix} $$
$$ \overline{m} = \begin{bmatrix} 1 - i & 2 \\ 3 + i & 4 - 2i \end{bmatrix}$$

In [190]:
import numpy as np
def format_complex(c):
    if (c.imag == 1 or c.imag == -1):
        if(c.real == 0):
            return f"{'      '}i{'   '}" 
        else:
            return f"{c.real}{' + ' if c.imag >= 0 else ' - '}i{'   '}"
    if (c.imag == 0):
        return f"{c.real}{'       '}"
    elif(c.real == 0):
        if (c.imag < 0):
            return f"{'     '}{c.imag}i"
        else:
            return f"{'      '}{c.imag}i"
    return f"{c.real}{' + ' if c.imag >= 0 else ' - '}{abs(c.imag)}i"

def format_printed(a,b):
    print("El conjugado de la matriz")
    m = 0
    for i in a:
        if (m > 0):
            m += 1
            print("       ", ' '.join(format_complex(x) for x in i) )
        else:
            m += 1
            print("   m = ", ' '.join(format_complex(x) for x in i))
    print()
    m = 0
    for i in b:
        if (m > 0):
            m += 1
            print("       ", ' '.join(format_complex(x) for x in i) )
        else:
            m += 1
            print("   es: ", ' '.join(format_complex(x) for x in i))
    print()

def conjugate_matriz(a):
    a = np.array(a)
    conjugate = np.conjugate(a)
    format_printed(a,conjugate)

m = [[1+1j,2],[3-1j,4+2j]]
conjugate_matriz(m)

El conjugado de la matriz
   m =  1.0 + i    2.0       
        3.0 - i    4.0 + 2.0i

   es:  1.0 - i    2.0       
        3.0 + i    4.0 - 2.0i



### Exercise 11: Transpose of a Complex Matrix
Find the transpose of the complex matrix 
$$ m = \begin{bmatrix} 1 - i & 2 + 2i \\ 3 & 4 - i \end{bmatrix} $$
$$ m^{T} = \begin{bmatrix} 1 - i & 3  \\2 + 2i & 4 - i \end{bmatrix} $$

In [191]:
import numpy as np
def format_complex(c):
    if (c.imag == 1 or c.imag == -1):
        if(c.real == 0):
            return f"{'      '}i{'   '}" 
        else:
            return f"{c.real}{' + ' if c.imag >= 0 else ' - '}i{'   '}"
    if (c.imag == 0):
        return f"{c.real}{'       '}"
    elif(c.real == 0):
        if (c.imag < 0):
            return f"{'     '}{c.imag}i"
        else:
            return f"{'      '}{c.imag}i"
    return f"{c.real}{' + ' if c.imag >= 0 else ' - '}{abs(c.imag)}i"

def format_printed(a,b):
    print("La transpuesta de la matriz")
    m = 0
    for i in a:
        if (m > 0):
            m += 1
            print("       ", '     '.join(format_complex(x) for x in i) )
        else:
            m += 1
            print("   m = ", '     '.join(format_complex(x) for x in i))
    print()
    m = 0
    for i in b:
        if (m > 0):
            m += 1
            print("       ", '     '.join(format_complex(x) for x in i) )
        else:
            m += 1
            print("   es: ", '     '.join(format_complex(x) for x in i))
    print()

def transpose_matrix(a):
    a = np.array(a)
    transpose = a.T
    format_printed(a,transpose)

m = [[1-1j,2+2j],[3,4-1j]]
transpose_matrix(m)



La transpuesta de la matriz
   m =  1.0 - i        2.0 + 2.0i
        3.0            4.0 - i   

   es:  1.0 - i        3.0       
        2.0 + 2.0i     4.0 - i   



### Exercise 12: Adjunct (Conjugate Transpose) of a Complex Matrix
Calculate the adjunct (or conjugate transpose) of the complex matrix 
$$ m = \begin{bmatrix} 1 + 2i & 3 - i \\ 4 & 5 + i \end{bmatrix} $$
$$ \overline{m^{T}}  = \begin{bmatrix} 1 - 2i & 4 \\ 3 + i & 5 - i \end{bmatrix}$$




In [192]:
import numpy as np
def format_complex(c):
    if (c.imag == 1 or c.imag == -1):
        if(c.real == 0):
            return f"{'      '}i{'   '}" 
        else:
            return f"{c.real}{' + ' if c.imag >= 0 else ' - '}i{'   '}"
    if (c.imag == 0):
        return f"{c.real}{'       '}"
    elif(c.real == 0):
        if (c.imag < 0):
            return f"{'     '}{c.imag}i"
        else:
            return f"{'      '}{c.imag}i"
    return f"{c.real}{' + ' if c.imag >= 0 else ' - '}{abs(c.imag)}i"

def format_printed(a,b):
    print("La transpuesta de la matriz")
    m = 0
    for i in a:
        if (m > 0):
            m += 1
            print("       ", '     '.join(format_complex(x) for x in i) )
        else:
            m += 1
            print("   m = ", '     '.join(format_complex(x) for x in i))
    print()
    m = 0
    for i in b:
        if (m > 0):
            m += 1
            print("       ", '     '.join(format_complex(x) for x in i) )
        else:
            m += 1
            print("   es: ", '     '.join(format_complex(x) for x in i))
    print()

def adjunct_matrix(a):
    a = np.array(a)
    adjunct = np.conjugate(a.T)
    format_printed(a,adjunct)

m = [[1+2j,3-1j],[4,5+1j]]
adjunct_matrix(m)

La transpuesta de la matriz
   m =  1.0 + 2.0i     3.0 - i   
        4.0            5.0 + i   

   es:  1.0 - 2.0i     4.0       
        3.0 + i        5.0 - i   



### Exercise 13: Checking the Dimensions of a Matrix
Determine the dimensions of the complex matrix 
$ m = \begin{bmatrix} 1 - i & 2 \\ 3 + 2i & 4 - i \end{bmatrix} $.


In [193]:
import numpy as np

def format_complex(c):
    if (c.imag == 1 or c.imag == -1):
        if(c.real == 0):
            return f"{'      '}i{'   '}" 
        else:
            return f"{c.real}{' + ' if c.imag >= 0 else ' - '}i{'   '}"
    if (c.imag == 0):
        return f"{c.real}{'       '}"
    elif(c.real == 0):
        if (c.imag < 0):
            return f"{'     '}{c.imag}i"
        else:
            return f"{'      '}{c.imag}i"
    return f"{c.real}{' + ' if c.imag >= 0 else ' - '}{abs(c.imag)}i"

def format_printed(a,b):
    print("La dimension de la matriz")
    m = 0
    for i in a:
        if (m > 0):
            m += 1
            print("       ", '     '.join(format_complex(x) for x in i) )
        else:
            m += 1
            print("   m = ", '     '.join(format_complex(x) for x in i))
    print("   es :", b[0], "x", b[1])


def dimension_matrix(a):
    a = np.array(a)
    dimensions = a.shape
    format_printed(a,dimensions)

m = [[1-1j,2],[3+2j,4-1j]]
dimension_matrix(m)

La dimension de la matriz
   m =  1.0 - i        2.0       
        3.0 + 2.0i     4.0 - i   
   es : 2 x 2


### Exercise 14: Multiplying a Complex Square Matrix by a Complex Column Vector
Multiply the complex square matrix 
$ m = \begin{bmatrix} 1 + i & 2 - i \\ 3 & 4 + i \end{bmatrix} $ 
by the complex column vector 
$ v = \begin{bmatrix} 2 - i \\ 1 + 3i \end{bmatrix} $.
$$
m \cdot v = \begin{bmatrix} (1 + i)(2 - i) + (2 - i)(1 + 3i) \\ 3(2 - i) + (4 + i)(1 + 3i) \end{bmatrix} = \begin{bmatrix} 8 + 6i \\ 7 + 10i \end{bmatrix}
$$



In [194]:
import numpy as np

def format_complex(c):
    if (c.imag == 1 or c.imag == -1):
        if(c.real == 0):
            return f"{'      '}i{'   '}" 
        else:
            return f"{c.real}{' + ' if c.imag >= 0 else ' - '}i{'   '}"
    if (c.imag == 0):
        return f"{c.real}{'       '}"
    elif(c.real == 0):
        if (c.imag < 0):
            return f"{'     '}{c.imag}i"
        else:
            return f"{'      '}{c.imag}i"
    return f"{c.real}{' + ' if c.imag >= 0 else ' - '}{abs(c.imag)}i"

def format_printed(a,b,c):
    print("La multiplicacion entre la matriz")
    m = 0
    for i in a:
        if (m > 0):
            m += 1
            print("       ", '     '.join(format_complex(x) for x in i) )
        else:
            m += 1
            print("   m = ", '     '.join(format_complex(x) for x in i))
    print("y el vector ")
    print("  v =  ",' \n        '.join(format_complex(x) for x in b))
    print()
    print(" es :  ",' \n        '.join(format_complex(x) for x in c))

def multiplication_Complex_Matrix_Vector(A,b):
    A = np.array(A)
    b = np.array(b)
    result = np.dot(A,b)
    format_printed(a,b,result)

m = [[1+1j,2-1j],[3,4+1j]]
v = [2-1j,1+3j]
multiplication_Complex_Matrix_Vector(m,v)


La multiplicacion entre la matriz
   m =  1.0 + i        2.0 - i   
        3.0 + 2.0i     4       
y el vector 
  v =   2.0 - i    
        1.0 + 3.0i

 es :   8.0 + 6.0i 
        7.0 + 10.0i
