# Hermitian Matrices, Unitary Matrices and Tensor Product


# Understanding Complex Hermitian and Unitary Matrices

This tutorial delves into two pivotal concepts in quantum computing and linear algebra: complex Hermitian and Unitary matrices. Both play critical roles in quantum mechanics and quantum computing, underpinning the behavior of quantum systems and the operations performed on them.

## Objectives
- Define and explore the properties of complex Hermitian matrices.
- Understand and implement complex Unitary matrices in Python.
- Highlight their significance and applications in quantum computing.

Prepare to enhance your mathematical toolkit with these foundational concepts, illustrated with Python examples for a hands-on learning experience.



## Complex Hermitian Matrices

A Hermitian matrix, or self-adjoint matrix, is a square matrix that is equal to its own conjugate transpose. This property makes it a natural representation of observable quantities in quantum mechanics.

### Properties
- The eigenvalues of a Hermitian matrix are always real.
- The eigenvectors of a Hermitian matrix corresponding to different eigenvalues are orthogonal.
- Hermitian matrices are extensively used in quantum mechanics to describe physical observables.

### Python Example: Defining a Hermitian Matrix


In [4]:

import numpy as np

# Define a complex Hermitian matrix
hermitian_matrix = np.array([[2+0j, 2-1j], [2+1j, 3+0j]])

# Check if the matrix is Hermitian
is_hermitian = np.allclose(hermitian_matrix, hermitian_matrix.conj().T)

is_hermitian, hermitian_matrix


(True,
 array([[2.+0.j, 2.-1.j],
        [2.+1.j, 3.+0.j]]))


## Complex Unitary Matrices

A Unitary matrix is a square matrix whose conjugate transpose is also its inverse. Unitary matrices preserve the inner product, making them essential for describing quantum gates and evolution in quantum computing.

### Properties
- Preserves the norm of vectors, hence preserving quantum states during transformations.
- The determinant of a Unitary matrix has an absolute value of 1.
- Used to represent reversible quantum operations and time evolution in quantum systems.

### Python Example: Defining a Unitary Matrix


In [5]:

# Define a complex Unitary matrix
unitary_matrix = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2)*1j, -1/np.sqrt(2)*1j]])

# Check if the matrix is Unitary
# np.eye(2) returns the identity of size 2x2
is_unitary = np.allclose(np.dot(unitary_matrix, unitary_matrix.conj().T), np.eye(2))

is_unitary, unitary_matrix


(True,
 array([[ 0.70710678+0.j        ,  0.70710678+0.j        ],
        [ 0.        +0.70710678j, -0.        -0.70710678j]]))

# Tensor product


## Tensor Product for Complex Vectors

The tensor product of two complex vectors creates a new vector in a higher-dimensional space, allowing us to combine quantum states in quantum computing.

### Example


In [6]:

import numpy as np

# Define two complex vectors for the tensor product
v1 = np.array([1+2j, 3+4j])
v2 = np.array([5+6j, 7+8j])

# Calculate the tensor product
tensor_product_v = np.kron(v1, v2)

tensor_product_v


array([ -7.+16.j,  -9.+22.j,  -9.+38.j, -11.+52.j])


## Tensor Product for Complex Matrices

The tensor product for matrices combines individual matrices into a larger matrix, crucial for representing multiple qubit systems in quantum computing.

### Example


In [7]:

# Define two complex matrices for the tensor product
M1 = np.array([[1+2j, 3+4j], [5+6j, 7+8j]])
M2 = np.array([[9+10j, 11+12j], [13+14j, 15+16j]])

# Calculate the tensor product
tensor_product_m = np.kron(M1, M2)

tensor_product_m


array([[-11. +28.j, -13. +34.j, -13. +66.j, -15. +80.j],
       [-15. +40.j, -17. +46.j, -17. +94.j, -19.+108.j],
       [-15.+104.j, -17.+126.j, -17.+142.j, -19.+172.j],
       [-19.+148.j, -21.+170.j, -21.+202.j, -23.+232.j]])

# Exercises on Complex Vector and Matrix Operations

This set of exercises is designed to test your understanding of various concepts related to complex vector and matrix operations, which are foundational in quantum computing. Each exercise presents a concrete case for you to apply what you've learned about Hermitian matrices, Unitary matrices, and tensor products.

NOTE: VERIFY YOUR COMPUTATIONS IN PAPER AND IN THE COMPUTER.

## Exercise 1: Complex Hermitian Matrices

Consider the matrix:

$$ H = \begin{bmatrix} 3 & 2+i \\ 2-i & 1 \end{bmatrix} $$

- Verify if $ H $ is a Hermitian matrix.
- If it is, find its eigenvalues.

## Exercise 2: Complex Unitary Matrices

Consider the matrix:

$$ U = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 & i \\ i & 1 \end{bmatrix} $$

- Verify if $ U $ is a Unitary matrix.
- Compute $ UU^\dagger $ to confirm its Unitarity, where $ U^\dagger $ denotes the conjugate transpose of $ U $.

## Exercise 3: Tensor Product for Complex Vectors

Given the complex vectors:

$$ \mathbf{v} = \begin{bmatrix} 1+i \\ 2-i \end{bmatrix}, \quad \mathbf{w} = \begin{bmatrix} 1-2i \\ 3 \end{bmatrix} $$

Calculate the tensor product $ \mathbf{v} \otimes \mathbf{w} $.

## Exercise 4: Tensor Product for Complex Matrices

Given the matrices:

$$ M_1 = \begin{bmatrix} 0 & 1 \\ 1 & 0 \end{bmatrix}, \quad M_2 = \begin{bmatrix} i & 0 \\ 0 & -i \end{bmatrix} $$

Calculate the tensor product $ M_1 \otimes M_2 $.

## Exercise 5: Modelling quantum computations with vectors and matrices

Using matrices and vectors, implement a model of the Mach/Zehnder interferometer.

![Mach-Zehnder interferometer](images/Mach-Zehnder-Interferometer.png)

## Exercise 6: Composing quantum systems 

Using matrices and vectors, implement a model of the following circuit.

![Mach-Zehnder interferometer](images/Deutsch-Algorithm.png)

Use the following MAtrix for $U_f$:

![Mach-Zehnder interferometer](images/ExampleUf.png)



<h1 style="text-align: center;">Solución de los Ejercicios</h1>


## Exercise 1: Complex Hermitian Matrices

Consider the matrix:

$$ H = \begin{bmatrix} 3 & 2+i \\ 2-i & 1 \end{bmatrix} $$

- Verify if $ H $ is a Hermitian matrix.
- If it is, find its eigenvalues.


In [60]:
import numpy as np

#funcion para quitarle los parentesis a los numero complejos, si una de sus partes es 0 también se elimina 
def format_complex(c):
    if (c.imag == 0):
        return f"{c.real}"
    elif(c.real == 0):
        return f"{c.imag}j"
    return f"{c.real}{' + ' if c.imag >= 0 else ' - '}{abs(c.imag)}j"

#funcion que utilizaremos si la matriz es hermitiana para imprimir los valores propios
def format_printed_hermitian(eigenvalues,a):
    format_print_matrix(a)
    print("ES hermitiana y sus valores propios son: ")
    print("")
    for i in range(len(eigenvalues)):
        print(f"ValorPropio{i+1}:",format_complex(eigenvalues[i]))

#Funcion para imprimir la matriz inicial
def format_print_matrix(a):
    print("La matriz ")
    m = 0
    for i in a:
        if (m > 0):
            m += 1
            print ("     ", ' '.join(format_complex(x) for x in i) )
        else:
            m += 1
            print(" H = ", ' '.join(format_complex(x) for x in i))

# Define a complex Hermitian matrix
H = np.array([[3, 2-1j], [2-1j, 1]])

#funcion que tiene la lógica para saber si es hermitiana y si lo es calcular sus valores propios 
def isHermitian(a):
    is_hermitian = np.allclose(a, a.conj().T)
    if is_hermitian== True:
        eigenvalues, eigenvectors = np.linalg.eig(a)
        format_printed_hermitian(eigenvalues,a)
    else:
        format_print_matrix(a)
        print("No es hermitiana ")
        
isHermitian(H)

La matriz 
 H =  3.0 2.0 - 1.0j
      2.0 - 1.0j 1.0
No es hermitiana 


## Exercise 2: Complex Unitary Matrices

Consider the matrix:

$$ U = \frac{1}{\sqrt{2}}\begin{bmatrix} 1 & i \\ i & 1 \end{bmatrix} $$

- Verify if $ U $ is a Unitary matrix.
- Compute $ UU^\dagger $ to confirm its Unitarity, where $ U^\dagger $ denotes the conjugate transpose of $ U $.


In [73]:
U = np.array([[1/np.sqrt(2), 1/np.sqrt(2)*1j], [1/np.sqrt(2)*1j, -1/np.sqrt(2)]])
unitary_matrix = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2)*1j, -1/np.sqrt(2)*1j]])

def format_print_matrix(a,t):
    m = 0
    for i in a:
        if (m > 0):
            m += 1
            print ("         ", '   '.join(format_complex(x) for x in i) )
        else:
            m += 1
            print(" ",t," = ", '   '.join(format_complex(x) for x in i))

def prove_unitary(U):
    uadjunct = U.conj().T
    print("Si calculamos su adjunta")
    format_print_matrix(uadjunct, "U✝ ")
    print("y está la multiplicamos por la matriz inicial ")
    format_print_matrix(U,"U  ")
    UUt = np.dot(U, uadjunct)
    print("El resultado es:")
    format_print_matrix(U,"UU✝")
    if(np.allclose(np.dot(U, U.conj().T), np.eye(2))):
        return "ES una matriz unitaria, ya que al hacer la operación UU✝ nos da la matriz identidad"
    return "NO es una matriz unitaria"

prove_unitary(U)



Si calculamos su adjunta
  U✝   =  0.7071067811865475   -0.7071067811865475j
          -0.7071067811865475j   -0.7071067811865475
y está la multiplicamos por la matriz inicial 
  U    =  0.7071067811865475   0.7071067811865475j
          0.7071067811865475j   -0.7071067811865475
El resultado es:
  UU✝  =  0.7071067811865475   0.7071067811865475j
          0.7071067811865475j   -0.7071067811865475


'NO es una matriz unitaria'

## Exercise 5: Modelling quantum computations with vectors and matrices

Using matrices and vectors, implement a model of the Mach/Zehnder interferometer.

![Mach-Zehnder interferometer](images/Mach-Zehnder-Interferometer.png)


Para resolver este ejercicio empezaremos de derecha a izquierda de la siguiente ecuación:
$$
|Y\rangle = |Y_3\rangle \times |Y_2\rangle \times |Y_1\rangle \times |Y_0\rangle
$$
Remplazando con los componentes del circuito no queda la siguiente escuación:
$$
|Y\rangle = H \cdot \left( X \cdot \left( H \cdot |0\rangle \right) \right)
$$


In [54]:
import numpy as np

def mach_Zehnder(Q0,H,X):
    y0 = Q0
    y1 = np.dot(H,y0)
    y2 = np.dot(X,y1)
    y3 = np.dot(H,y2)
    print(" |Y} =  H * ( X * ( H * |0〉) )")
    print(" |Y} =  ", end="")
    format_print(y3)

def format_print(vector):
    vector = np.round(vector,decimals=1)
    #Cambiamos de vector columna a vector fila para una iteración más simple  
    vector = vector.flatten() 
    a = []
    m = 0
    for x in vector:
        if x.is_integer():
            if (m == np.size(vector)-1):
                print("        ⌊", int(x), "⌋")
            elif (m > 0):
                print("        |", int(x), "|")
            else:
                print("⌈", int(x), "⌉")
            m += 1
        else:
            if (m == np.size(vector)-1):
                print("        ⌊", int(x), "⌋")
            elif (m > 0):
                print("        |", int(x), "|")
            else:
                print("⌈", int(x), "⌉")
            m += 1
    
Q0 = np.array([[1],[0]])
H = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2), -1/np.sqrt(2)]])
X = np.array([[0,1],[1,0]])

mach_Zehnder(Q0,H,X)

 |Y} =  H * ( X * ( H * |0〉) )
 |Y} =  ⌈ 1 ⌉
        ⌊ 0 ⌋


## Exercise 6: Composing quantum systems 

![Mach-Zehnder interferometer](images/Deutsch-Algorithm.png)

Use the following MAtrix for $U_f$:

![Mach-Zehnder interferometer](images/ExampleUf.png)

La ecuación para poder calcular la salida del circuito es:
$$
|Y\rangle = |Y_3\rangle \times |Y_2\rangle \times |Y_1\rangle \times |Y_0\rangle
$$
Remplazando con los componentes del circuito no queda la siguiente escuación:
$$
|Y\rangle = (H \otimes I) \cdot \left( U_f \cdot \left((H \otimes H) \cdot ( |0\rangle \otimes |1\rangle  )\right)\right)
$$

In [53]:
import numpy as np

def format_print(vector):
    
    vector = np.round(vector,decimals=8)
    #Cambiamos de vector columna a vector fila para una iteración más simple  
    vector = vector.flatten() 
    m = 0
    for x in vector:
        if x.is_integer() and x == 0.00000000:
            if (m == np.size(vector)-1):
                print("       ⌊     ", 0, "     ⌋")
            elif (m > 0):
                print("       |     ", 0, "     |")
            else:
                print("⌈     ", 0, "     ⌉")
            m += 1
        elif x > 0:
            if (m == np.size(vector)-1):
                print("       ⌊ ", x, "⌋")
            elif (m > 0):
                print("       | ", x, "|")
            else:
                print("⌈ ", x, "⌉")
            m += 1
        else:
            if (m == np.size(vector)-1):
                print("       ⌊", x, "⌋")
            elif (m > 0):
                print("       |", x, "|")
            else:
                print("⌈", x, "⌉")
            m += 1

#Función que calcula el  producto tensor de matrices y vectores columna
def product_tensor(a,b):
    result = np.kron(a, b)
    return result

#Función que calcula el producto de una matriz y un vector columna

def product_vector_matrix(v, M):
    result = np.dot(M, v)
    return result

#Función que calcula el |y} del circuito
    
def deutsch(Q0,Q1,H,Uf,identidad):
    y0 = product_tensor(Q0,Q1)
    y1 = product_vector_matrix(y0,product_tensor(H,H))
    y2 = product_vector_matrix(y1,Uf)
    y3 = product_vector_matrix(y2,product_tensor(H,identidad))
    print(" |Y} = (H ⊗ I) *( Uf * ((H ⊗ H ) * ( |0〉 ⊗ |1〉 )))")
    print(" |Y} = ", end="")
    format_print(y3)

#definicion de las matrices y vectores columna del circuito

Q0 = np.array([[1],[0]])
Q1 = np.array([[0],[1]])
H = np.array([[1/np.sqrt(2), 1/np.sqrt(2)], [1/np.sqrt(2), -1/np.sqrt(2)]])
Uf = np.array([[0,1,0,0],[1,0,0,0],[0,0,1,0],[0,0,0,1]])
identidad = np.array([[1,0],[0,1]])

# Llamada de la función y sus respectivas matrices y vectores del circuito 
deutsch(Q0,Q1,H,Uf,identidad)




 |Y} = (H ⊗ I) *( Uf * ((H ⊗ H ) * ( |0〉 ⊗ |1〉 )))
 |Y} = ⌈      0      ⌉
       |      0      |
       | -0.70710678 |
       ⌊  0.70710678 ⌋
